# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/template/
      - eng/
      - build.gradle
      - gradle.properties
      - settings.gradle

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/template/
      - eng/
      - build.gradle
      - gradle.properties
      - settings.gradle

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: template
    Artifacts:
      - name: azure-sdk-template
        safeName: azuresdktemplate
        groupId: com.azure.android
