resources:
  repositories:
    - repository: azure-sdk-build-tools
      type: git
      name: internal/azure-sdk-build-tools
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure

trigger:
  branches:
    include:
      - master
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/communication/

pr:
  branches:
    include:
      - master
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/communication/

stages:
  - template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
    parameters:
      ServiceDirectory: communication
      Artifacts:
        - name: azure-communication-common
          safeName: azurecommunicationcommon
          groupId: com.azure.android
        - name: azure-communication-chat
          safeName: azurecommunicationchat
          groupId: com.azure.android
