# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/communication/

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/communication/

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: communication
    Artifacts:
      - name: azure-communication-common
        safeName: azurecommunicationcommon
        groupId: com.azure.android
      - name: azure-communication-chat
        safeName: azurecommunicationchat
        groupId: com.azure.android