trigger: none

extends:
  template: /eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  parameters:
    Repository: $(Build.Repository.Name)
    Prefix: android
    CIConventionOptions: ''
    UPConventionOptions: '--variablegroups 1 58 76'
    TestsConventionOptions: ''
