trigger: none

extends:
  template: /eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  parameters:
    Repository: $(Build.Repository.Name)
    Prefix: android
    CIConventionOptions: ''
    UPConventionOptions: '--variablegroup 1 --variablegroup 58 --variablegroup 76 --variablegroup 56'
    TestsConventionOptions: ''
