parameters:
  - name: ServiceDirectory
    type: string
  - name: Artifacts
    type: object

jobs:
  - job: 'Build'

    variables:
      - template: ../variables/globals.yml

    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - script: |
          ./gradlew sdk:${{parameters.ServiceDirectory}}:build

  - job: 'Analyze'

    variables:
      - template: ../variables/globals.yml

    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - script: |
          echo Hello, world!
        displayName: A task