parameters:
  ServiceDirectory: not-specified # Set a default that breaks in obvious ways.
  Artifacts: []

jobs:
  - job: 'Build'

    variables:
      - template: ../variables/globals.yml

    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - script: |
          ./gradlew sdk:${{parameters.ServiceDirectory}}:build sdk:${{parameters.ServiceDirectory}}:publish
        displayName: Build packages
      - ${{ each artifact in parameters.Artifacts }}:
        - pwsh: |
            Get-ChildItem sdk/${{parameters.ServiceDirectory}}/${{artifact.name}}/build/repo/**/${{artifact.name}} -Recurse | Where-Object -FilterScript { $_.Name -match "(jar|pom|aar)$" }
            #$stagingLocation = New-Item -Type Directory -Path $(Build.ArtifactStagingDirectory) -Name ${{artifact.name}}
            #$artifactsToStage | Copy-Item -Destination $stagingLocation
          displayName: Stage ${{artifact.name}} for upload
      # - publish: $(Build.ArtifactStagingDirectory)
      #   artifact: packages
      #   displayName: Upload artifacts

  - job: 'Analyze'

    variables:
      - template: ../variables/globals.yml

    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - script: |
          echo Hello, world!
        displayName: A task