// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

/**
 * Internal implementations and inner classes used by the Azure Communication Chat Service client library.
 */
package com.azure.android.communication.chat.implementation;
