// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.android.storage.blob.models;

import com.azure.android.core.http.ResponseBase;

import okhttp3.Headers;
import okhttp3.Request;

/**
 * Contains all response data for the getProperties operation.
 */
public final class BlobGetPropertiesResponse extends ResponseBase<BlobGetPropertiesHeaders, Void> {
    /**
     * Creates an instance of {@link BlobGetPropertiesResponse}.
     *
     * @param request             The request which resulted in this BlobsGetPropertiesResponse.
     * @param statusCode          The status code of the HTTP response.
     * @param rawHeaders          The raw headers of the HTTP response.
     * @param value               The deserialized value of the HTTP response.
     * @param deserializedHeaders The deserialized headers of the HTTP response.
     */
    public BlobGetPropertiesResponse(Request request,
                                     int statusCode,
                                     Headers rawHeaders,
                                     Void value,
                                     BlobGetPropertiesHeaders deserializedHeaders) {
        super(request, statusCode, rawHeaders, value, deserializedHeaders);
    }
}
