// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package com.azure.android.storage.blob.models;

import com.azure.android.core.util.CoreUtil;

import org.threeten.bp.OffsetDateTime;

/**
 * Type representing result of Stage Block API.
 */
public class StageBlockResult {
    private final byte[] contentMD5;
    private final OffsetDateTime dateProperty;
    private final byte[] xMsContentCrc64;
    private final Boolean isServerEncrypted;
    private final String encryptionKeySha256;

    /**
     * Creates StageBlockResult.
     *
     * @param contentMD5          The MD5 value of the staged block computed by the Blob service.
     * @param date                The UTC date/time value generated by the Blob service that indicates
     *                            the time at which the response was initiated.
     * @param xMsContentCrc64     The xMsContentCrc64 value of the staged block computed by the Blob service.
     * @param isServerEncrypted   Indicates if the contents of the request are successfully encrypted if requested.
     * @param encryptionKeySha256 The SHA-256 hash of the encryption key used to encrypt the block.
     */
    public StageBlockResult(byte[] contentMD5,
                            OffsetDateTime date,
                            byte[] xMsContentCrc64,
                            Boolean isServerEncrypted,
                            String encryptionKeySha256) {
        this.contentMD5 = contentMD5;
        this.dateProperty = date;
        this.xMsContentCrc64 = xMsContentCrc64;
        this.isServerEncrypted = isServerEncrypted;
        this.encryptionKeySha256 = encryptionKeySha256;
    }

    /**
     * Get the MD5 value of the staged block computed by the Blob service.
     *
     * @return the contentMD5 value.
     */
    public byte[] getContentMD5() {
        return CoreUtil.clone(this.contentMD5);
    }

    /**
     * Get the xMsContentCrc64 value of the staged block computed by the Blob service.
     *
     * @return the xMsContentCrc64 value.
     */
    public byte[] getXMsContentCrc64() {
        return CoreUtil.clone(this.xMsContentCrc64);
    }

    /**
     * Get the UTC date/time value generated by the
     * Blob service that indicates the time at which the response was initiated.
     *
     * @return the dateProperty value.
     */
    public OffsetDateTime getDate() {
        return this.dateProperty;
    }

    /**
     * True if the contents of the request are successfully encrypted if encryption
     * was requested, and false otherwise.
     *
     * @return the isServerEncrypted value.
     */
    public Boolean isServerEncrypted() {
        return this.isServerEncrypted;
    }

    /**
     * Get the SHA-256 hash of the encryption key used to encrypt the block.
     * The value is only returned when the block was encrypted with a
     * customer-provided key.
     *
     * @return the encryptionKeySha256 value.
     */
    public String getEncryptionKeySha256() {
        return this.encryptionKeySha256;
    }
}
