// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// A Type that will be generated by AutoRest.Android.

package com.azure.android.storage.blob.implementation.models;

import com.azure.android.core.util.CancellationToken;
import com.azure.android.storage.blob.models.CpkInfo;

import org.threeten.bp.OffsetDateTime;

/**
 * The optional parameters for GetBlobProperties API.
 */
public class GetBlobPropertiesOptions {
    private String snapshot;
    private Integer timeout;
    private String version;
    private String leaseId;
    private String ifMatch;
    private String ifNoneMatch;
    private OffsetDateTime ifModifiedSince;
    private OffsetDateTime ifUnmodifiedSince;
    private String requestId;
    private CpkInfo cpkInfo;
    private CancellationToken cancellationToken;

    /**
     * Create GetBlobPropertiesOptions.
     */
    public GetBlobPropertiesOptions() {
    }

    /**
     * Get the snapshot value.
     *
     * @return The snapshot value.
     */
    public String getSnapshot() {
        return snapshot;
    }

    /**
     * Set the snapshot value.
     *
     * The snapshot parameter is an opaque DateTime value that, when present, specifies the blob snapshot to retrieve.
     * For more information on working with blob snapshots,
     * see &lt;a href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/creating-a-snapshot-of-a-blob"&gt;Creating a Snapshot of a Blob.&lt;/a&gt;.
     *
     * @param snapshot The snapshot value.
     * @return The updated GetBlobPropertiesOptions object.
     */
    public GetBlobPropertiesOptions setSnapshot(String snapshot) {
        this.snapshot = snapshot;
        return this;
    }

    /**
     * Get the timeout value.
     *
     * @return The timeout value.
     */
    public Integer getTimeout() {
        return timeout;
    }

    /**
     * Set= the timeout value.
     *
     * The timeout parameter is expressed in seconds. For more information,
     * see &lt;a href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting Timeouts for Blob Service Operations.&lt;/a&gt;.
     *
     * @param timeout The timeout value.
     * @return The updated GetBlobPropertiesOptions object.
     */
    public GetBlobPropertiesOptions setTimeout(Integer timeout) {
        this.timeout = timeout;
        return this;
    }

    /**
     * Get the version value.
     *
     * @return The version value.
     */
    public String getVersion() {
        return version;
    }

    /**
     * Set the version.
     *
     * Specifies the version of the operation to use for this request.
     *
     * @param version The version.
     * @return The updated GetBlobPropertiesOptions object.
     */
    public GetBlobPropertiesOptions setVersion(String version) {
        this.version = version;
        return this;
    }

    /**
     * Set the ifMatch value.
     *
     * Limit requests to resources that match the provided ETag.
     *
     * @param ifMatch ifMatch value.
     *
     * @return The updated GetBlobPropertiesOptions object.
     */
    public GetBlobPropertiesOptions setIfMatch(String ifMatch) {
        this.ifMatch = ifMatch;
        return this;
    }

    /**
     * Get the ifMatch value.
     *
     * @return The ifMatch value.
     */
    public String getIfMatch() {
        return ifMatch;
    }

    /**
     * Set the ifNoneMatch value.
     *
     * Limit requests to resources that do not match the provided ETag.
     *
     * @param ifNoneMatch ifNoneMatch value.
     * @return The updated GetBlobPropertiesOptions object.
     */
    public GetBlobPropertiesOptions setIfNoneMatch(String ifNoneMatch) {
        this.ifNoneMatch = ifNoneMatch;
        return this;
    }

    /**
     * Get the ifNoneMatch value.
     *
     * @return The ifMatch value.
     */
    public String getIfNoneMatch() {
        return ifNoneMatch;
    }

    /**
     * Set the ifModifiedSince value.
     *
     * Limit requests to resources that have only been modified since the provided OffsetDateTime.
     *
     * @param ifModifiedSince The ifModifiedSince value.
     * @return The updated GetBlobPropertiesOptions object.
     */
    public GetBlobPropertiesOptions setIfModifiedSince(OffsetDateTime ifModifiedSince) {
        this.ifModifiedSince = ifModifiedSince;
        return this;
    }

    /**
     * Get the ifModifiedSince value.
     *
     * @return The ifModifiedSince value.
     */
    public OffsetDateTime getIfModifiedSince() {
        return ifModifiedSince;
    }

    /**
     * Set the ifUnmodifiedSince value.
     *
     * Limit requests to resources that have remained unmodified since the the provided OffsetDateTime.
     *
     * @param ifUnmodifiedSince The ifUnmodifiedSince value.
     * @return The updated GetBlobPropertiesOptions object.
     */
    public GetBlobPropertiesOptions setIfUnmodifiedSince(OffsetDateTime ifUnmodifiedSince) {
        this.ifUnmodifiedSince = ifUnmodifiedSince;
        return this;
    }

    /**
     * Get the ifUnmodifiedSince value.
     *
     * @return The ifUnmodifiedSince value.
     */
    public OffsetDateTime getIfUnmodifiedSince() {
        return ifUnmodifiedSince;
    }

    /**
     * Get the leaseId value.
     *
     * @return The leaseId value.
     */
    public String getLeaseId() {
        return leaseId;
    }

    /**
     * Set the leaseId value.
     *
     * If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     *
     * @param leaseId The leaseId value.
     * @return The updated GetBlobPropertiesOptions object.
     */
    public GetBlobPropertiesOptions setLeaseId(String leaseId) {
        this.leaseId = leaseId;
        return this;
    }

    /**
     * Get the requestId value.
     *
     * @return The requestId value.
     */
    public String getRequestId() {
        return requestId;
    }


    /**
     * Set the requestId value.
     *
     * Provides a client-generated, opaque value with a 1 KB character limit that is recorded in the analytics
     * logs when storage analytics logging is enabled.
     *
     * @param requestId The requestId value.
     * @return The updated GetBlobPropertiesOptions object.
     */
    public GetBlobPropertiesOptions setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }

    /**
     * Get the cpkInfo value.
     *
     * @return The cpkInfo value.
     */
    public CpkInfo getCpkInfo() {
        return cpkInfo;
    }

    /**
     * Set the cpkInfo value.
     *
     * @param cpkInfo The cpkInfo value.
     * @return The updated GetBlobPropertiesOptions object.
     */
    public GetBlobPropertiesOptions setCpkInfo(CpkInfo cpkInfo) {
        this.cpkInfo = cpkInfo;
        return this;
    }

    /**
     * Get the CancellationToken value.
     *
     * @return The CancellationToken value.
     */
    public CancellationToken getCancellationToken() {
        return this.cancellationToken == null ? CancellationToken.NONE : cancellationToken;
    }

    /**
     * Set the CancellationToken value.
     *
     * @param cancellationToken the cancellationToken value.
     * @return The updated GetBlobPropertiesOptions object.
     */
    public GetBlobPropertiesOptions setCancellationToken(CancellationToken cancellationToken) {
        this.cancellationToken = cancellationToken;
        return this;
    }
}
