# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

resources:
  repositories:
    - repository: azure-sdk-build-tools
      type: git
      name: internal/azure-sdk-build-tools
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure

trigger:
  branches:
    include:
      - master
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/core/
      - eng/
      - build.gradle
      - gradle.properties
      - settings.gradle

pr:
  branches:
    include:
      - master
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/core/
      - eng/
      - build.gradle
      - gradle.properties
      - settings.gradle
      
stages:
  - template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
    parameters:
      ServiceDirectory: core
      Artifacts:
        - name: azure-core
          safeName: azurecore
