parameters:
  - name: Artifacts
    type: object
    default: []
  - name: ArtifactName
    type: string
    default: 'not-specified'
  - name: DependsOn
    type: object
  - name: VerifyVersions
    type: string
    default: 'not-specified'

stages:
  # The signing stage is responsible for submitting binaries to ESRP for our official signing
  # where appropriate and also meeting any other signing requirements for particular artifacts,
  # in this case we do GPG signing in order to publish to Maven Central. At the moment signing
  # is protected by an approval check but this may be removed in the future.
  - stage: Signing
    dependsOn: ${{parameters.DependsOn}}
    jobs:
      - deployment: SignPackage
        environment: esrp
        timeoutInMinutes: 20
        pool:
          name: azsdk-pool-mms-ubuntu-2004-general
          image: azsdk-pool-mms-ubuntu-2004-1espt
          os: linux

        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - checkout: azure-sdk-build-tools
                  path: azure-sdk-build-tools

                - download: current
                  artifact: ${{parameters.ArtifactName}}
                  timeoutInMinutes: 5

                - template: /tools/java-esrp-signing/java-esrp-signing.yml@azure-sdk-build-tools
                  parameters:
                    Artifacts: ${{parameters.Artifacts}}
                    ArtifactDirectory: $(Pipeline.Workspace)/${{parameters.ArtifactName}}
                
                - template: /eng/common/pipelines/templates/steps/publish-1es-artifact.yml
                  parameters:
                    ArtifactName: ${{parameters.ArtifactName}}-signed
                    ArtifactPath: $(Pipeline.Workspace)/${{parameters.ArtifactName}}

  # We generate two interdependent stages for each artifact listed in the ci.yml file, creates the release
  # in GitHub. The Release stage publishes to Maven Central. Both stages require approval since they
  # effectively burn the version number. For testing of packages prior to burning the version number -
  # the Validation step below publishes a package to a "burner" feed which is cleaned up after the
  # pipeline completes.
  - ${{if and(eq(variables['Build.Reason'], 'Manual'), eq(variables['System.TeamProject'], 'internal'))}}:
    - ${{ each artifact in parameters.Artifacts }}:
      - stage: Release_${{artifact.safeName}}
        displayName: 'Release: ${{artifact.name}}'
        dependsOn: Signing
        condition: and(succeeded(), ne(variables['SetDevVersion'], 'true'), ne(variables['Skip.Release'], 'true'), ne(variables['Build.Repository.Name'], 'Azure/azure-sdk-for-android-pr'))
        jobs:
          - deployment: TagRepository
            displayName: "Create release tag"
            condition: ne(variables['Skip.TagRepository'], 'true')
            environment: maven
            timeoutInMinutes: 5
            dependsOn:
              - ${{ if eq(parameters.VerifyVersions, 'true')}}:
                - VerifyReleaseVersion

            pool:
              name: azsdk-pool-mms-win-2022-general
              image: azsdk-pool-mms-win-2022-1espt
              os: windows

            strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: self
                    - download: current
                      displayName: 'Download Artifact: ${{parameters.ArtifactName}}-signed'
                      artifact: ${{parameters.ArtifactName}}-signed
                    - template: /eng/common/pipelines/templates/steps/create-tags-and-git-release.yml
                      parameters:
                        ArtifactLocation: $(Pipeline.Workspace)/${{parameters.ArtifactName}}-signed/${{artifact.safeName}}
                        PackageRepository: Maven
                        ReleaseSha: $(Build.SourceVersion)

          - ${{if ne(artifact.options.skipPublishPackage, 'true')}}:
            - deployment: PublishPackage
              displayName: "Publish to Maven Central"
              condition: and(succeeded(), ne(variables['Skip.PublishPackage'], 'true'))
              environment: maven
              dependsOn: TagRepository

              pool:
                name: azsdk-pool-mms-win-2022-general
                image: azsdk-pool-mms-win-2022-1espt
                os: windows

              strategy:
                runOnce:
                  deploy:
                    steps:
                      - checkout: self
                      - checkout: azure-sdk-build-tools
                        path: azure-sdk-build-tools
                      - template: tools/gpg/gpg.yml@azure-sdk-build-tools
                      - template: /eng/common/pipelines/templates/steps/sparse-checkout.yml
                        parameters:
                          SkipCheckoutNone: true
                          Repositories:
                            - Name: Azure/azure-sdk-for-android
                              Commitish: $(Build.SourceVersion)
                              WorkingDirectory: $(Pipeline.Workspace)/azure-sdk-for-android

                      - template: /eng/pipelines/templates/steps/java-publishing.yml
                        parameters:
                          ArtifactID: ${{artifact.name}}
                          GroupID: ${{artifact.groupId}}
                          ArtifactDirectory: $(Pipeline.Workspace)/${{parameters.ArtifactName}}-signed
                          OutputDirectory: $(Pipeline.Workspace)/EsrpPackages
                          Target: EsrpRelease
                          # Note: In spite of the fact that the variable is named JavaRepoRoot, the
                          # root needs to be the root of the android repository
                          JavaRepoRoot: $(Pipeline.Workspace)/azure-sdk-for-android

                      - template: /eng/common/pipelines/templates/steps/publish-1es-artifact.yml
                        parameters:
                          ArtifactName: ${{parameters.ArtifactName}}-${{artifact.name}}-esrp-$(System.JobAttempt)
                          ArtifactPath: $(Pipeline.Workspace)/EsrpPackages

          - ${{if ne(artifact.options.skipPublishDocs, 'true')}}:
            - deployment: PublishDocs
              displayName: Publish Docs to GitHubIO Blob Storage
              condition: and(succeeded(), ne(variables['Skip.PublishDocs'], 'true'))
              environment: maven
              dependsOn: PublishPackage

              pool:
                name: azsdk-pool-mms-win-2022-general
                image: azsdk-pool-mms-win-2022-1espt
                os: windows

              strategy:
                runOnce:
                  deploy:
                    steps:
                      - template: /eng/common/pipelines/templates/steps/sparse-checkout.yml
                      - download: current
                        displayName: 'Download Artifact: ${{parameters.ArtifactName}}-signed'
                        artifact: ${{parameters.ArtifactName}}-signed
                        patterns: ${{artifact.safeName}}/**
                      - pwsh: |
                          Get-ChildItem -Recurse $(Pipeline.Workspace)/${{parameters.ArtifactName}}-signed/${{artifact.safeName}}
                        workingDirectory: $(Pipeline.Workspace)
                        displayName: Output Visible Artifacts
                      - template: /eng/common/pipelines/templates/steps/publish-blobs.yml
                        parameters:
                          FolderForUpload: '$(Pipeline.Workspace)/${{parameters.ArtifactName}}-signed/${{artifact.safeName}}'
                          TargetLanguage: 'android'
                          ArtifactLocation: $(Pipeline.Workspace)/${{parameters.ArtifactName}}-signed/${{artifact.safeName}}
