parameters:
  - name: ServiceDirectory
    type: string
  - name: Artifacts
    type: object

resources:
  repositories:
    - repository: azure-sdk-build-tools
      type: git
      name: internal/azure-sdk-build-tools
    - repository: azure-sdk-tools  
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure

trigger:    
  branches:
    include:
      - dev
      - feature/*
      - hotfix/*
      - release/*
  paths:  
    include:
      - sdk/${{parameters.ServiceDirectory}}/

pr:    
  branches:
    include:
      - dev
      - feature/*
      - hotfix/*
      - release/*
  paths:  
    include:
      - sdk/${{parameters.ServiceDirectory}}/
              
stages:
  - stage: Build
    jobs:
    - template: ../jobs/archetype-sdk-client.yml
      parameters:
        ServiceDirectory: ${{parameters.ServiceDirectory}}
        Artifacts: ${{parameters.Artifacts}}

  # The Prerelease and Release stages are conditioned on whether we are building a pull request and the branch.
  - ${{if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'internal'))}}:
    - template: pipelines/stages/archetype-java-release.yml@azure-sdk-build-tools
      parameters:
        DependsOn: Build
        Artifacts: ${{parameters.Artifacts}}
        ArtifactName: packages